### ISSUE TITLE
Adapter httproute resolving issue

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#1139]
**Description:**
Tried the sample api given in the tryout/samples. Then applied them successfully.
Then remove one httproute (prod-http-route-http-bin-api-p2) and update.

getting this error. `API deployment failed for UPDATE event : scope: pet has not been resolved in namespace apk`

```
apiVersion: dp.wso2.com/v1alpha1
kind: API
metadata:
  name: http-bin-api
spec:
  apiDisplayName: http-bin-api
  apiType: REST
  apiVersion: 1.0.8
  context: /http-bin-api/1.0.8
  definitionFileRef: swagger-definition-http-bin-api
  production:
    - httpRouteRefs:
      - prod-http-route-http-bin-api-p1
      - prod-http-route-http-bin-api-p2
  sandbox:
    - httpRouteRefs:
      - sand-http-route-http-bin-api
  organization: a3b58ccf-6ecc-4557-b5bb-0a35cce38256
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
