### ISSUE TITLE
Custom ratelimits with for key groups

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#1147]
**Description:**
Need to support custom ratelimits with only key. i.e.
if we defined per key should have 4 req per min, we should be able to define it without creating multiple ratelimit policies for each key value.

**Proposed solution**

```
apiVersion: dp.wso2.com/v1alpha1
kind: RateLimitPolicy
metadata:
  name: http-bin-ratelimit-user
spec:
  override:
    type: Custom
    custom:
      key: rlkey_user
      # value: bob
      rateLimit:
        requestsPerUnit: 4
        unit: Minute
    organization: a3b58ccf-6ecc-4557-b5bb-0a35cce38256
  targetRef:
    kind: Gateway
    name: default
    group: gateway.networking.k8s.io
```
by making the above spec.override.custom.value optional we can achieve this. 
If no value has given, then it means each user would get 4 req per min.
i.e. user alice would get 4 req per min, user bob will also get 4 req per min

If we specify a value bob, then only bob will get ratelimitted after 4 requests, where as others users such as alice would not get ratemitted.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
