### ISSUE TITLE
Issue in Wildcard resources

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#1192]
**Description:**
When an API was created with wildcard resources, trailing slash getting appended to the backend request path

sample path:
```
- backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: backend-eab0c3e1f3f8d5c4977d2d6bec7e1e52f4d6b887-api
      namespace: apk
      weight: 1
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replaceFullPath: /get\1
          type: ReplaceFullPath
    - extensionRef:
        group: dp.wso2.com
        kind: Authentication
        name: a204a55167fa8178ac834bea1e6bc575d782d745-production-authentication
      type: ExtensionRef
```

step 1: create a api with backend http://httpbin/get with wildcard resources.
step 2: invoke /get -> backend /get/ getting invoked

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
