### ISSUE TITLE
[Config-Deployer] Need to provide both production and sandbox vhosts

### ISSUE THREAD

**Issue by menakaj** [wso2/apk#1250]
**Description:**

When using the config-deployer service to generate k8s artifacts providing the apk.conf file, both the production and sandbox vhosts need to be provided.

The service also crashes with the error below.
```
time = 2023-06-14T13:14:51.681+05:30 level = INFO module = wso2/config_deployer_service message = "Initializing Runtime Domain Service.."
error: {ballerina}TypeCastError {"message":"incompatible types: '()' cannot be cast to 'string[]'"}
	at wso2.config_deployer_service.0:getHostNames(APIClient.bal:476)
	   wso2.config_deployer_service.0:putHttpRouteForPartition(APIClient.bal:457)
	   wso2.config_deployer_service.0:setHttpRoute(APIClient.bal:442)
	   wso2.config_deployer_service.0:generateK8sArtifacts(APIClient.bal:86)
	   wso2.config_deployer_service.0:prepareArtifact(APIClient.bal:1350)
	   wso2.config_deployer_service.0.ConfigGeneratorClient:getGeneratedK8sResources(ConfigGenreatorClient.bal:129)
	   wso2.config_deployer_service.0.$anonType$_2:$post$apis$generate-k8s-resources(artifact-generator-api_service.bal:25)
```
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1. Generate apk.conf
2. Populate missing parameters, and only provide the production vhost

```
name: "Awesome2Petstore"
id: "a3b58ccf-6ecc-4557-b5bb-0a35cce38256"
context: "/test"
version: "1.0.0"
type: "REST"
organization: "wso2"
endpointConfigurations:
    production:
        endpoint: "https://petstore3.swagger.io/api/v3"
operations:
    - target: "/find"
      verb: "GET"
      authTypeEnabled: true
    - target: "/pet/findByStatus"
      verb: "GET"
      authTypeEnabled: true
vhosts:
  production:
    - "https://a3b58ccf-6ecc-4557-b5bb-0a35cce38256.dev.dev-us-east-azure.choreo.dev"
```
3. Invoke the /generate-k8s-resources with the apk.conf and swager file.

**Related Issues:**
