### ISSUE TITLE
Adapter throwing indefinite error logs

### ISSUE THREAD

**Issue by Tharsanan1** [wso2/apk#1341]
**Description:**
When applying ratelimit CRs getting indefinite error logs in the adapter side.

**Suggested Labels:**
Bug

**Steps to reproduce:**
Apply the followinf CRs and look at the adapter logs.

```
apiVersion: dp.wso2.com/v1alpha1
kind: Backend
metadata:
  name: backend-svc
spec:
  services:
  - host: backend.apk
    port: 80
    
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
        - image: docker.io/kennethreitz/httpbin:latest
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "200Mi"
              cpu: "300m"
            limits:
              memory: "200Mi"
              cpu: "300m"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: analytics-route
spec:
  hostnames:
  - analytics.gw.wso2.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: default
    sectionName: httpslistener
  rules:
  - backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: backend-svc
    matches:
    - path:
        type: PathPrefix
        value: /analytics-api/v1
    filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
---
apiVersion: dp.wso2.com/v1alpha1
kind: API
metadata:
  name: analytics-api2
spec:
  apiDisplayName: Analytics Test API
  apiType: REST
  apiVersion: v1
  context: /analytics-api/v1
  production:
    - httpRouteRefs:
      - analytics-route
---
apiVersion: dp.wso2.com/v1alpha1
kind: RateLimitPolicy
metadata:
  name: analytics-ratelimit
spec:
  default:
    type: Api
    api:
      rateLimit:
        requestsPerUnit: 5
        unit: Minute
  targetRef:
    kind: API
    name: analytics-api2
    group: gateway.networking.k8s.io


```

You will see errors similar to this 

```
2023-07-04 07:11:56 ERRO [router_callbacks.go:64] - [routercallbacks.(*Callbacks).OnStreamRequest] [-] Stream request for type type.googleapis.com/envoy.config.route.v3.RouteConfiguration on stream id: 1, from node: default:apk-test-wso2-apk-gateway-runtime-deployment-54f969b8b6-tbhd7, Error: Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[3]: embedded message failed validation | caused by VirtualHostValidationError.Routes[1]: embedded message failed validation | caused by RouteValidationError.Route: embedded message failed validation | caused by RouteActionValidationError.RateLimits[0]: embedded message failed validation | caused by RateLimitValidationError.Actions[0]: embedded message failed validation | caused by ActionValidationError.GenericKey: embedded message failed validation | caused by GenericKeyValidationError.DescriptorValue: value length must be at least 1 characters): name: "httpslistener"
virtual_hosts {
  name: "api.am.wso2.com"
  domains: "api.am.wso2.com"
  domains: "api.am.wso2.com:*"
  routes {
    match {
      path: "/api/runtime/1.0.0"
      headers {
        name: ":method"
        string_match {
          safe_regex {
            regex: "^GET$"
          }
        }
      }
      query_parameters {
        name: "definitionType"
        string_match {
          exact: "OAS"
        }
      }
    }
    route {
      cluster: "api_definition_cluster"
      prefix_rewrite: "/api/runtime/1.0.0/api.am.wso2.com?OAS"
      auto_host_rewrite {
        value: true
      }
    }
    decorator {
      operation: "/api/runtime/1.0.0"
    }
    typed_per_filter_config {
      key: "envoy.filters.http.ext_authz"
      value {
        [type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute] {
          disabled: true
        }
      }
    }
    name: "OAS"
  }
  routes {
    match {
      headers {
        name: ":method"
        string_match {
          safe_regex {
            regex: "^GET|OPTIONS$"
          }
        }
      }
      safe_regex {
        regex: "^/api/runtime/apis([/]{0,1})"
      }
    }
    route {
      cluster_header: "x-wso2-cluster-header"
      auto_host_rewrite {
        value: true
      }
      upgrade_configs {
        upgrade_type: "websocket"
        enabled {
        }
      }
      regex_rewrite {
        pattern {
          regex: "^/api/runtime/apis([/]{0,1})"
        }
        substitution: "/api/runtime/apis"
      }
    }
    decorator {
      operation: "api.am.wso2.com:^/api/runtime/apis([/]{0,1})"
    }
    typed_per_filter_config {
      key: "envoy.filters.http.cors"
      value {
        [type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy] {
        }
      }
    }
    typed_per_filter_config {
      key: "envoy.filters.http.ext_authz"
      value {
        [type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute] {
          check_settings {
            context_extensions {
              key: "basePath"
              value: "/api/runtime/1.0.0"
            }
            context_extensions {
              key: "clusterName"
              value: "carbon.super__api.am.wso2.com_RuntimeDomainServiceAPI1.0.0_a002e8d2-24a8-4f44-93ff-77cb030cff8d0"
            }
            context_extensions {
              key: "method"
              value: "GET"
            }
            context_extensions {
              key: "name"
              value: "Runtime Domain Service API"
            }
            context_extensions {
              key: "path"
              value: "/api/runtime/apis"
            }
            context_extensions {
              key: "vHost"
              value: "api.am.wso2.com"
            }
            context_extensions {
              key: "version"
              value: "1.0.0"
            }
            disable_request_body_buffering: true
          }
        }
      }
    }
    typed_per_filter_config {
      key: "envoy.filters.http.lua.local"
      value {
        [type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute] {
          disabled: true
        }
      }
    }
    name: "/api/runtime/1.0.0"
  }
  routes {
    match {
      headers {
        name: ":method"
        string_match {
          safe_regex {
            regex: "^POST|OPTIONS$"
          }
        }
      }
      safe_regex {
        regex: "^/api/runtime/api...(truncated) [severity=Critical error_code=1401]
```
