### ISSUE TITLE
CORs policy not working with methods

### ISSUE THREAD

**Issue by Tharsanan1** [wso2/apk#1430]
**Description:**
When adding CORs policy it enables CORs for all the http methods. If I add specific Http methods under 'accessControlAllowMethods' other HTTP methods also get enabled

**Suggested Labels:**
Bug

**Steps to reproduce:**
Follow the QSG and add the following cors config to the apk-conf
```
corsConfiguration:
  corsConfigurationEnabled: true
  accessControlAllowCredentials: true
  accessControlAllowOrigins:
  - "*"
  accessControlAllowHeaders:
  - authorization
  accessControlAllowMethods:
  - GET
  # - POST
  accessControlExposeHeaders:
  - "*"
```

invoke the Post request from browser and you will get 200.
