### ISSUE TITLE
Config deployer is crashing when it does not have all the properties in the authentication

### ISSUE THREAD

**Issue by Tharsanan1** [wso2/apk#1432]
**Description:**
When using the following apk-conf with QSG config deployer is crashing 

```
---
name: "EmployeeServiceAPI"
context: "/test"
version: "3.14"
type: "REST"
organization: "apk-org"
defaultVersion: true
endpointConfigurations:
  production:
    endpoint: "https://run.mocky.io/v3/85516819-1edd-412b-a32b-a9284705a0b4"
operations:
- target: "/employee"
  verb: "GET"
  authTypeEnabled: true
  scopes: []
- target: "/employee"
  verb: "POST"
  authTypeEnabled: true
  scopes: []
  # operationRateLimit: 
  #   requestsPerUnit: 3
  #   unit: "Minute"
- target: "/employee/{employeeId}"
  verb: "PUT"
  authTypeEnabled: true
  scopes: []
- target: "/employee/{employeeId}"
  verb: "DELETE"
  authTypeEnabled: true
  scopes: []
vhosts:
  production:
  - "default.gw.wso2.com"
apiRateLimit:
  requestsPerUnit: 5
  unit: "Minute"
# corsConfiguration:
#   corsConfigurationEnabled: true
#   accessControlAllowCredentials: true
#   accessControlAllowOrigins:
#   - "*"
#   accessControlAllowHeaders:
#   - authorization
#   accessControlAllowMethods:
#   - GET
#   # - POST
#   accessControlExposeHeaders:
#   - "*"
authentication: 
  - authType: "JWT"
    enabled: true

```

error logs 

[2023-07-19 09:27:09,276] TRACE {http.tracelog.downstream} - [id: 0xee0743d9, correlatedSource: n/a, host:/172.17.0.21:9443 - remote:/172.17.0.1:2076] READ COMPLETE  
error: {ballerina}TypeCastError {"message":"incompatible types: '()' cannot be cast to 'string'"}
	at wso2.config_deployer_service.0:populateAuthenticationMap(APIClient.bal:286)
	   wso2.config_deployer_service.0:generateK8sArtifacts(APIClient.bal:96)
	   wso2.config_deployer_service.0:prepareArtifact(APIClient.bal:1374)
	   wso2.config_deployer_service.0:handleAPIDeployment(DeployerClient.bal:17)
	   wso2.config_deployer_service.0.$anonType$_1:$post$apis$deploy(artifact-deployer-api_service.bal:14)
[2023-07-19 09:27:09,485] TRACE {http.tracelog.downstream} - [id: 0xee0743d9, correlatedSource: n/a, host:/172.17.0.21:9443 - remote:/172.17.0.1:2076] OUTBOUND: DefaultFullHttpResponse(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 51, cap: 51, components=1))
HTTP/1.1 500 Internal Server Error
content-type: text/plain
content-length: 51
server: ballerina
date: Wed, 19 Jul 2023 09:27:09 GMT, 51B
incompatible types: '()' cannot be cast to 'string'  
[2023-07-19 09:27:09,486] TRACE {http.tracelog.downstream} - [id: 0xee0743d9, correlatedSource: n/a, host:/172.17.0.21:9443 - remote:/172.17.0.1:2076] FLUSH
