### ISSUE TITLE
Unable to disable authentication using config deployer

### ISSUE THREAD

**Issue by Tharsanan1** [wso2/apk#1436]
**Description:**
Unable to disable authentication using the following apk-conf

```
---
name: "EmployeeServiceAPI"
context: "/test"
version: "3.14"
type: "REST"
organization: "apk-org"
defaultVersion: true
endpointConfigurations:
  production:
    endpoint: "https://run.mocky.io/v3/85516819-1edd-412b-a32b-a9284705a0b4"
operations:
- target: "/employee"
  verb: "GET"
  authTypeEnabled: true
  scopes: []
- target: "/employee"
  verb: "POST"
  authTypeEnabled: true
  scopes: []
  # operationRateLimit: 
  #   requestsPerUnit: 3
  #   unit: "Minute"
- target: "/employee/{employeeId}"
  verb: "PUT"
  authTypeEnabled: true
  scopes: []
- target: "/employee/{employeeId}"
  verb: "DELETE"
  authTypeEnabled: true
  scopes: []
vhosts:
  production:
  - "default.gw.wso2.com"
apiRateLimit:
  requestsPerUnit: 5
  unit: "Minute"
authentication: 
- authType: JWT
  enabled: false
  sendTokenToUpstream: true
  headerName: Authorization
  headerEnable: true
```
