### ISSUE TITLE
Unable to undeploy and redeploy API 

### ISSUE THREAD

**Issue by Tharsanan1** [wso2/apk#1459]
**Description:**
While undeploying the following API i am getting 500, when i try to redeploy also I am getting 500. This is because there is some problem in deleting the backend cr. 

try deploy the following API

```

---
name: "EmployeeServiceAPI"
context: "/test"
version: "3.14"
type: "REST"
organization: "apk-org"
defaultVersion: true
endpointConfigurations:
  production:
    endpoint: "https://run.mocky.io/v3/85516819-1edd-412b-a32b-a9284705a0b4"
  sandbox:
    endpoint: "https://run.mocky.io/v3/4bf0062b-042e-4adf-b8c9-7be0cf8745cb"
operations:
- target: "/employee"
  verb: "GET"
  authTypeEnabled: true
  scopes: []
- target: "/employee"
  verb: "POST"
  authTypeEnabled: true
  scopes: []
- target: "/employee/{employeeId}"
  verb: "PUT"
  authTypeEnabled: true
  scopes: []
- target: "/employee/{employeeId}"
  verb: "DELETE"
  authTypeEnabled: true
  scopes: []
vhosts:
  production:
  - "default.gw.wso2.com"
  # sandbox: 
  # - "sand.gw.wso2.com"
apiRateLimit:
  requestsPerUnit: 5
  unit: "Minute"
```

Try to undeploy it. you will get 500. try to redeploy the same this again you will get 500.

Please note that we have added sandbox endpoint to the api level endpoints but not to the vhost. This is causing the problem something related backend cr. Either we have to validate the apk conf we get and throw 400. or we should fix this behavior. 

 in the log you will see the following

```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"backends.dp.wso2.com \"backend-2913eba66aa5d493889cc3f59562077aea70fba9-api\" already exists","reason":"AlreadyExists","details":{"name":"backend-2913eba66aa5d493889cc3f59562077aea70fba9-api","group":"dp.wso2.com","kind":"backends"},"code":409}
  
time = 2023-07-21T10:11:47.120Z level = ERROR module = wso2/config_deployer_service message = "Internal Error occured while deploying API" error = "{ballerina/lang.value}ConversionError"
error: Internal error occured while deploying API {"code":909028,"message":"Internal error occured while deploying API","statusCode":500,"description":"Internal error occured while deploying API","moreInfo":{}}
	at wso2.config_deployer_service.0:e909028(Errors.bal:290)
	   wso2.config_deployer_service.0:deployAPIToK8s(DeployerClient.bal:139)
	   wso2.config_deployer_service.0:handleAPIDeployment(DeployerClient.bal:18)
	   wso2.config_deployer_service.0.$anonType$_1:$post$apis$deploy(artifact-deployer-api_service.bal:14)
[2023-07-21 10:11:47,168] TRACE {http.tracelog.downstream} - [id: 0x14f69d29, correlatedSource: n/a, host:/172.17.0.9:9443 - remote:/172.17.0.1:35694] OUTBOUND: DefaultFullHttpResponse(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 146, cap: 146, components=1))
HTTP/1.1 500 Internal Server Error
content-type: application/json
content-length: 146
server: ballerina
date: Fri, 21 Jul 2023 10:11:47 GMT, 146B
{"code":909028, "message":"Internal error occured while deploying API", "description":"Internal error occured while deploying API", "moreInfo":{}}  
```
