### ISSUE TITLE
Interceptor policies are not working when added from the apk-conf

### ISSUE THREAD

**Issue by SavinduDimal** [wso2/apk#1498]
### Description
When interceptors are added as API-level or resource level policies from apk-conf file, they do not work as intended when the backendURL points to a k8s service.

```
apiPolicies:
  request:
    - policyName: "Interceptor"
      policyVersion: v1
      parameters:
        backendUrl: "http://interceptor-service.test-apk.svc.cluster.local:8443"
        headersEnabled: true
```

In the backend CR generated for the interceptor base path is added as an empty string. 

```
apiVersion: dp.wso2.com/v1alpha1
kind: Backend
metadata:
  name: backend-1dae10f7e7f06e5af130f489c3b4abcd9d920d51-interceptor
  namespace: apk
spec:
  basePath: ""
  protocol: http
  services:
  - host: interceptor-service.test-apk.svc.cluster.local
    port: 8443
```

When the `basePath` is removed, interceptors are working as expected.
