### ISSUE TITLE
Configuration baseIntervalMillis is not updating from apk-conf

### ISSUE THREAD

**Issue by SavinduDimal** [wso2/apk#1517]
### Description

- When adding backend retryPolicy configuration from `apk-conf` file baseIntervalMillis value is set to default value.

apk-conf:
```
endpointConfigurations:
  production:
    endpoint: "http://Savindu.local:3001"
    resiliency:
      retryPolicy:
        count: 3
        baseIntervalInMillis: 10
        statusCodes:
        - 418
 ```

backendCR:
```
apiVersion: dp.wso2.com/v1alpha1
kind: Backend
metadata:
  name: backend-e52fabf779bbe013c26a328a63c66c2e1a6fe345-api
  namespace: apk
spec:
  basePath: ""
  protocol: http
  retry:
    baseIntervalMillis: 2000
    count: 3
    statusCodes:
    - 418
  services:
  - host: Savindu.local
    port: 3001
```
