### ISSUE TITLE
Circuit Breaker maxRetries configuration does not work

### ISSUE THREAD

**Issue by SavinduDimal** [wso2/apk#1518]
### Description

Following configurations were added to an `apk-conf` file to configure circuit breaker and retry policy for backend.

```
endpointConfigurations:
  production:
    endpoint: "http://Savindu.local:3001"
    resiliency:
      retryPolicy:
        count: 5
        baseIntervalInMillis: 10
        statusCodes:
        - 418
      circuitBreaker:
        maxRequests: 2
        maxRetries: 2
```

After deploying backend CR and config dump has been updated with the given configurations. However, when the API is invoked it was observed 5 retries in the backend server instead of 2.
