### ISSUE TITLE
Improve httproutes creation

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#1527]
**Description:**
when api crs created from the config deployer it adds backend refs for each match. it make the httproute cr unnecessarily lengthier. it could be just add upper level backend refs affecting to all matches as follows.

```
  rules:
  - backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: backend-svc
    matches:
    - path:
        type: RegularExpression
        value: /books
      method: POST
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
