### ISSUE TITLE
Empty path has been added to httproute

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#1528]
**Description:**

when crs were created for the api in - https://raw.githubusercontent.com/Kong/swagger-ui-kong-theme/main/demo/public/specs/httpbin.yaml from the config deployer httproutes contained the following empty route.
```
  - matches:
    - path:
        type: "RegularExpression"
        value: ""  # <- empty value
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "" # <-empty
    backendRefs:
    - group: "dp.wso2.com"
      kind: "Backend"
      name: "backend-50fd665e4699bfdc21d6a5a2d977747b423ec561-api"
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
