### ISSUE TITLE
Issue in apiproperties

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#1534]
**Description:**
interceptor recieve some non empty values when properties haven't event configured .
maybe this only happens for post resources.
```
apiProperties = "{'propertyName1':'propertyValue1','propertyName2':'propertyValue2'}"
```
```
---
kind: "InterceptorService"
apiVersion: "dp.wso2.com/v1alpha1"
metadata:
  name: "response-interceptor-service-0-268309bb509758d0ec2ac03f96929cbb001e10cb-resource"
  labels:
    api-name: "de574cb5033a46c4ebc5cceba2117fc997c8c5ed"
    api-version: "91e95be6b6634e3c21072dfcd661146728694326"
    organization: "ca660bf19297d26c4d75e181527267301974a2cc"
    managed-by: "apk"
spec:
  backendRef:
    name: "backend-fc2d44b898e23f44130517865cc529a9d9c0cd5c-interceptor"
  includes:
  - "response_headers"
  - "response_body"
  - "response_trailers"
  - "invocation_context"
status: null
```
```
kind: "API"
apiVersion: "dp.wso2.com/v1alpha1"
metadata:
  name: "268309bb509758d0ec2ac03f96929cbb001e10cb"
  labels:
    api-name: "de574cb5033a46c4ebc5cceba2117fc997c8c5ed"
    api-version: "91e95be6b6634e3c21072dfcd661146728694326"
    organization: "ca660bf19297d26c4d75e181527267301974a2cc"
    managed-by: "apk"
spec:
  apiDisplayName: "InterceptorAPI"
  apiType: "REST"
  apiVersion: "1.0.0"
  context: "/interceptor/1.0.0"
  organization: "apk-org"
  isDefaultVersion: true
  definitionFileRef: "268309bb509758d0ec2ac03f96929cbb001e10cb-definition"
  production:
  - httpRouteRefs:
    - "01ee2d30-6919-1260-b370-dfe749da03ea"
  sandbox: null
  apiProperties: []
status: null
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
