### ISSUE TITLE
Add proper error messages for invalid operations and endpoint configs

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/apk#1560]
**Description:**
Need to add proper error messages for invalid operations and endpoint configs.

The following invalid operation config gives a type cast error.
```yaml
operations:
    - verb: "GET"
      authTypeEnabled: true
      scopes: []
```
