### ISSUE TITLE
Error encountered while invoking composite API 

### ISSUE THREAD

**Issue by Lakith-Rambukkanage** [wso2/apk#1666]
**Description:**
Invoking the API returned the following errors

```bash
curl -k --location 'https://default.gw.wso2.com:9095/composite/1.0.0/anything' \
--header 'Host: default.gw.wso2.com' \
--header 'Authorization: bearer eyJhbGciOiJSUzI1NiIsICJ0eXAiOiJKV1QiLCAia2lkIjoiZ2F0ZXdheV9jZXJ0aWZpY2F0ZV9hbGlhcyJ9.eyJpc3MiOiJodHRwczovL2lkcC5hbS53c28yLmNvbS90b2tlbiIsICJzdWIiOiI0NWYxYzVjOC1hOTJlLTExZWQtYWZhMS0wMjQyYWMxMjAwMDIiLCAiZXhwIjoxNjkyODY5MTA3LCAibmJmIjoxNjkyODY1NTA3LCAiaWF0IjoxNjkyODY1NTA3LCAianRpIjoiMDFlZTQyNTctYmI3YS0xMzNlLWE0ZTEtMjdkNzU5NDM5YjliIiwgImNsaWVudElkIjoiNDVmMWM1YzgtYTkyZS0xMWVkLWFmYTEtMDI0MmFjMTIwMDAyIiwgInNjb3BlIjoiZGVmYXVsdCJ9.A9PDDjaUQhSOTrmA1BkciuS76SH3KH7WRkkYgDHVD8W_QUaDtixqyGHFGlfrW9ABZuoI39RtoR-W20I3R8TAlzzl-6pK63pwVNNj7B9GIgXrgIP4c0WvvOigrAOiPoKa8rAR570FjBAiNLCZsbHWzL2kHAmqAnTyPMQ97lFHzoggHfGBf0PANyiR2elrRVA6Y6SITAiqOhv7DF5IVk_nUgRmGG1AEHH-gHs36Zl3lLLh1W1-ewOchidi9qiysZildnNuTQflynecYq8IskBE3h0A1qbkKXxlL5kTA1HG7XBr9_y0uTsKSxfS9I54cR_Y1JXKGaqKZxHt6xGR_ajL7Q'

curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to default.gw.wso2.com:9095


curl -k --location 'https://default.gw.wso2.com:9095/composite/1.0.0/anything' \
--header 'Host: default.gw.wso2.com' \
--header 'Authorization: bearer eyJhbGciOiJSUzI1NiIsICJ0eXAiOiJKV1QiLCAia2lkIjoiZ2F0ZXdheV9jZXJ0aWZpY2F0ZV9hbGlhcyJ9.eyJpc3MiOiJodHRwczovL2lkcC5hbS53c28yLmNvbS90b2tlbiIsICJzdWIiOiI0NWYxYzVjOC1hOTJlLTExZWQtYWZhMS0wMjQyYWMxMjAwMDIiLCAiZXhwIjoxNjkyODY5MTA3LCAibmJmIjoxNjkyODY1NTA3LCAiaWF0IjoxNjkyODY1NTA3LCAianRpIjoiMDFlZTQyNTctYmI3YS0xMzNlLWE0ZTEtMjdkNzU5NDM5YjliIiwgImNsaWVudElkIjoiNDVmMWM1YzgtYTkyZS0xMWVkLWFmYTEtMDI0MmFjMTIwMDAyIiwgInNjb3BlIjoiZGVmYXVsdCJ9.A9PDDjaUQhSOTrmA1BkciuS76SH3KH7WRkkYgDHVD8W_QUaDtixqyGHFGlfrW9ABZuoI39RtoR-W20I3R8TAlzzl-6pK63pwVNNj7B9GIgXrgIP4c0WvvOigrAOiPoKa8rAR570FjBAiNLCZsbHWzL2kHAmqAnTyPMQ97lFHzoggHfGBf0PANyiR2elrRVA6Y6SITAiqOhv7DF5IVk_nUgRmGG1AEHH-gHs36Zl3lLLh1W1-ewOchidi9qiysZildnNuTQflynecYq8IskBE3h0A1qbkKXxlL5kTA1HG7XBr9_y0uTsKSxfS9I54cR_Y1JXKGaqKZxHt6xGR_ajL7Q'

curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to default.gw.wso2.com:9095


curl -k --location 'https://default.gw.wso2.com:9095/composite/1.0.0/anything' \
--header 'Host: default.gw.wso2.com' \
--header 'Authorization: bearer eyJhbGciOiJSUzI1NiIsICJ0eXAiOiJKV1QiLCAia2lkIjoiZ2F0ZXdheV9jZXJ0aWZpY2F0ZV9hbGlhcyJ9.eyJpc3MiOiJodHRwczovL2lkcC5hbS53c28yLmNvbS90b2tlbiIsICJzdWIiOiI0NWYxYzVjOC1hOTJlLTExZWQtYWZhMS0wMjQyYWMxMjAwMDIiLCAiZXhwIjoxNjkyODY5MTA3LCAibmJmIjoxNjkyODY1NTA3LCAiaWF0IjoxNjkyODY1NTA3LCAianRpIjoiMDFlZTQyNTctYmI3YS0xMzNlLWE0ZTEtMjdkNzU5NDM5YjliIiwgImNsaWVudElkIjoiNDVmMWM1YzgtYTkyZS0xMWVkLWFmYTEtMDI0MmFjMTIwMDAyIiwgInNjb3BlIjoiZGVmYXVsdCJ9.A9PDDjaUQhSOTrmA1BkciuS76SH3KH7WRkkYgDHVD8W_QUaDtixqyGHFGlfrW9ABZuoI39RtoR-W20I3R8TAlzzl-6pK63pwVNNj7B9GIgXrgIP4c0WvvOigrAOiPoKa8rAR570FjBAiNLCZsbHWzL2kHAmqAnTyPMQ97lFHzoggHfGBf0PANyiR2elrRVA6Y6SITAiqOhv7DF5IVk_nUgRmGG1AEHH-gHs36Zl3lLLh1W1-ewOchidi9qiysZildnNuTQflynecYq8IskBE3h0A1qbkKXxlL5kTA1HG7XBr9_y0uTsKSxfS9I54cR_Y1JXKGaqKZxHt6xGR_ajL7Q'

curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to default.gw.wso2.com:9095


curl -k --location 'https://default.gw.wso2.com:9095/composite/1.0.0/anything' \
--header 'Host: default.gw.wso2.com' \
--header 'Authorization: bearer eyJhbGciOiJSUzI1NiIsICJ0eXAiOiJKV1QiLCAia2lkIjoiZ2F0ZXdheV9jZXJ0aWZpY2F0ZV9hbGlhcyJ9.eyJpc3MiOiJodHRwczovL2lkcC5hbS53c28yLmNvbS90b2tlbiIsICJzdWIiOiI0NWYxYzVjOC1hOTJlLTExZWQtYWZhMS0wMjQyYWMxMjAwMDIiLCAiZXhwIjoxNjkyODY5MTA3LCAibmJmIjoxNjkyODY1NTA3LCAiaWF0IjoxNjkyODY1NTA3LCAianRpIjoiMDFlZTQyNTctYmI3YS0xMzNlLWE0ZTEtMjdkNzU5NDM5YjliIiwgImNsaWVudElkIjoiNDVmMWM1YzgtYTkyZS0xMWVkLWFmYTEtMDI0MmFjMTIwMDAyIiwgInNjb3BlIjoiZGVmYXVsdCJ9.A9PDDjaUQhSOTrmA1BkciuS76SH3KH7WRkkYgDHVD8W_QUaDtixqyGHFGlfrW9ABZuoI39RtoR-W20I3R8TAlzzl-6pK63pwVNNj7B9GIgXrgIP4c0WvvOigrAOiPoKa8rAR570FjBAiNLCZsbHWzL2kHAmqAnTyPMQ97lFHzoggHfGBf0PANyiR2elrRVA6Y6SITAiqOhv7DF5IVk_nUgRmGG1AEHH-gHs36Zl3lLLh1W1-ewOchidi9qiysZildnNuTQflynecYq8IskBE3h0A1qbkKXxlL5kTA1HG7XBr9_y0uTsKSxfS9I54cR_Y1JXKGaqKZxHt6xGR_ajL7Q'

{"description":"The requested resource is not available.","message":"Not Found","code":"404"}
```

`scene9_api_1.apk-conf`

```yaml
name: compositeAPI
context: /composite
version: 1.0.0
type: REST
defaultVersion: false
authentication:
  - authType: JWT
    headerName: X-JWT-Token
operations:
  - target: "/headers"
    authTypeEnabled: false
    scopes: []
    verb: GET
    endpointConfigurations:
      production:
        endpoint: "https://httpbin.org/headers"
      sandbox:
        endpoint: "https://httpbin.org/headers"
  - target: "/anything"
    authTypeEnabled: false
    scopes: []
    verb: POST
    endpointConfigurations:
      production:
        endpoint: "https://httpbin.org/anything/post"
      sandbox:
        endpoint: "https://httpbin.org/anything/post"
```

`scene9_api_1_oas3.yaml`

```yaml
openapi: 3.0.0
info:
  title: "compositeAPI"
  version: "1.0.0"
  contact:
    name: Contact Name
    email: contact@example.com
    url: https://example.com/
tags:
  - name: Metadata
    description: Metadata related requests
components:
  headers:
    X-JWT-Token:
      description: JWT Token
      schema:
        type: string
        format: JWT
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT authentication
paths:
  /headers:
    get:
      operationId: get_headers
      summary: Get headers
      servers:
        - url: https://httpbin.org/headers
      responses:
        '200':
          description: OK
      security:
        - JWT: []
  /anything:
    post:
      operationId: get_resource2
      summary: Get resource2
      servers:
        - url: https://httpbin.org/anything/post
      responses:
        '200':
          description: OK
```
