### ISSUE TITLE
Received the 504 Gateway Time-out error intermittently

### ISSUE THREAD

**Issue by Lakith-Rambukkanage** [wso2/apk#1667]
**Description:**
Received the following error from time to time while invoking a resource

```bash
curl --location 'https://default.gw.wso2.com:9095/composite/1.0.0/anything?valpk=apkkey' \
--header 'Host: default.gw.wso2.com' \
--header 'Authorization: bearer eyJhbGciOiJSUzI1NiIsICJ0eXAiOiJKV1QiLCAia2lkIjoiZ2F0ZXdheV9jZXJ0aWZpY2F0ZV9hbGlhcyJ9.eyJpc3MiOiJodHRwczovL2lkcC5hbS53c28yLmNvbS90b2tlbiIsICJzdWIiOiI0NWYxYzVjOC1hOTJlLTExZWQtYWZhMS0wMjQyYWMxMjAwMDIiLCAiZXhwIjoxNjkyODcyODg1LCAibmJmIjoxNjkyODY5Mjg1LCAiaWF0IjoxNjkyODY5Mjg1LCAianRpIjoiMDFlZTQyNjAtODc1Ny0xNDBlLTliOTYtZTYxODBhYmNhNjI4IiwgImNsaWVudElkIjoiNDVmMWM1YzgtYTkyZS0xMWVkLWFmYTEtMDI0MmFjMTIwMDAyIiwgInNjb3BlIjoiZGVmYXVsdCJ9.HiddQSfMEs52RIl3I9cfLwimuQA3q_RPB6PNAkC1UE1swn3lwcIEahPm9Xs3akYu9nZEBMx7jnSWVN-ZvF6dOMiNHHk62TZ4hzHWtBJsG281y-J7QJWIT25qDy7rvHAr3SmffG72E7Ba1WN-9aSCOTM381diFeZ5uiWiLTVGSlhRapuMu-Sch1NoSFjN4XPR-7e2oHp3jm57RthxkLge7tLYUr--TWiUdg8yo82rBSRMw8TWw23h4FZzFzCDfe843tXsQxzmPr8zDEkepztEg5ujh-yiSRElEPcHcAhy_3iEDeu7qmX-Ljo9SkYi0j2oxuTVlE_2RWLia1-BK8cEOw' \
--header 'Content-Type: text/plain' \
--data '{
    "echo": "valecho"
}' -k
{"message":"Upstream connection timeout","description":"upstream request timeout","code":"102504"}
curl --location 'https://default.gw.wso2.com:9095/composite/1.0.0/anything?valpk=apkkey' \
--header 'Host: default.gw.wso2.com' \
--header 'Authorization: bearer eyJhbGciOiJSUzI1NiIsICJ0eXAiOiJKV1QiLCAia2lkIjoiZ2F0ZXdheV9jZXJ0aWZpY2F0ZV9hbGlhcyJ9.eyJpc3MiOiJodHRwczovL2lkcC5hbS53c28yLmNvbS90b2tlbiIsICJzdWIiOiI0NWYxYzVjOC1hOTJlLTExZWQtYWZhMS0wMjQyYWMxMjAwMDIiLCAiZXhwIjoxNjkyODcyODg1LCAibmJmIjoxNjkyODY5Mjg1LCAiaWF0IjoxNjkyODY5Mjg1LCAianRpIjoiMDFlZTQyNjAtODc1Ny0xNDBlLTliOTYtZTYxODBhYmNhNjI4IiwgImNsaWVudElkIjoiNDVmMWM1YzgtYTkyZS0xMWVkLWFmYTEtMDI0MmFjMTIwMDAyIiwgInNjb3BlIjoiZGVmYXVsdCJ9.HiddQSfMEs52RIl3I9cfLwimuQA3q_RPB6PNAkC1UE1swn3lwcIEahPm9Xs3akYu9nZEBMx7jnSWVN-ZvF6dOMiNHHk62TZ4hzHWtBJsG281y-J7QJWIT25qDy7rvHAr3SmffG72E7Ba1WN-9aSCOTM381diFeZ5uiWiLTVGSlhRapuMu-Sch1NoSFjN4XPR-7e2oHp3jm57RthxkLge7tLYUr--TWiUdg8yo82rBSRMw8TWw23h4FZzFzCDfe843tXsQxzmPr8zDEkepztEg5ujh-yiSRElEPcHcAhy_3iEDeu7qmX-Ljo9SkYi0j2oxuTVlE_2RWLia1-BK8cEOw' \
--header 'Content-Type: text/plain' \
--data '{
    "echo": "valecho"
}' -k
{
  "args": {
    "valpk": "apkkey"
  },
  "data": "{\n    \"echo\": \"valecho\"\n}",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Content-Length": "25",
    "Content-Type": "text/plain",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.82.0",
    "X-Amzn-Trace-Id": "Root=1-64e72522-1cd63aff5e2f97a754a99f10"
  },
  "json": {
    "echo": "valecho"
  },
  "method": "POST",
  "origin": "203.94.95.4",
  "url": "https://httpbin.org/anything/post/anything?valpk=apkkey"
}
```

```html
<html>

<head>
	<title>504 Gateway Time-out</title>
</head>

<body>
	<center>
		<h1>504 Gateway Time-out</h1>
	</center>
</body>

</html>
```

**test artifacts**

`scene9_api_1.apk-conf`

```yaml
name: compositeAPI
context: /composite
version: 1.0.0
type: REST
defaultVersion: false
authentication:
  - authType: JWT
    headerName: X-JWT-Token
operations:
  - target: "/headers"
    authTypeEnabled: true
    scopes: []
    verb: GET
    endpointConfigurations:
      production:
        endpoint: "https://httpbin.org/headers"
      sandbox:
        endpoint: "https://httpbin.org/headers"
  - target: "/anything"
    authTypeEnabled: true
    scopes: []
    verb: POST
    endpointConfigurations:
      production:
        endpoint: "https://httpbin.org/anything/post"
      sandbox:
        endpoint: "https://httpbin.org/anything/post"
```

`scene9_api_1_oas2.yaml`

```yaml
openapi: 3.0.0
info:
  title: "compositeAPI"
  version: "1.0.0"
  contact:
    name: Contact Name
    email: contact@example.com
    url: https://example.com/
tags:
  - name: Metadata
    description: Metadata related requests
components:
  headers:
    X-JWT-Token:
      description: JWT Token
      schema:
        type: string
        format: JWT
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT authentication
paths:
  /headers:
    get:
      operationId: get_headers
      summary: Get headers
      servers:
        - url: https://httpbin.org/headers
      responses:
        '200':
          description: OK
      security:
        - JWT: []
  /anything:
    post:
      operationId: get_resource2
      summary: Get resource2
      servers:
        - url: https://httpbin.org/anything/post
      responses:
        '200':
          description: OK
```
