### ISSUE TITLE
VSCode extension gives syntax error for CORS accessControlExposeHeaders

### ISSUE THREAD

**Issue by sgayangi** [wso2/apk#1703]
**Description:**
When adding the CORS configuration as follows (https://apk.docs.wso2.com/en/latest/create-api/create-and-attach-api-policies/cors/enable-cors-via-rest-api/)
```
corsConfiguration:
  corsConfigurationEnabled: true
  accessControlAllowCredentials: true
  accessControlAllowOrigins:
    - "*"
  accessControlAllowHeaders:
    - authorization
  accessControlAllowMethods:
    - GET
  accessControlExposeHeaders:
    - "*"
```
VSCode highlights the accessControlExposeHeaders and gives the syntax error 
```
Property accessControlExposeHeaders is not allowed.yaml-schema: apkschema://schema/apk-conf
```
There is no issue in deploying the API with this field.
