### ISSUE TITLE
Issue when invoking API having both api level and resource level endpoints

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/apk#1704]
**Description:**
If the API has both API level and resource level endpoints as follows,

```
name: "EmployeeAPI4"
context: "/test4"
version: "1.3"
type: "REST"
defaultVersion: false
endpointConfigurations:
  production:
    endpoint: "https://run.mocky.io/v3/c13ca99f-b8de-4545-8167-bef2f699f071"
  sandbox:
    endpoint: "https://run.mocky.io/v3/85516819-1edd-412b-a32b-a9284705a0b4"
operations:
- target: "/employee"
  endpointConfigurations:
    sandbox:
      endpoint: "https://run.mocky.io/v3/7c78e8c4-2a57-4dfe-8054-30e59a247d47"
  verb: "GET"
  authTypeEnabled: true
  scopes: []
- target: "/employee"
  verb: "POST"
  authTypeEnabled: true
  scopes: []
- target: "/employee1234"
  verb: "GET"
  authTypeEnabled: true
  scopes: []
- target: "/employee/{employeeId}"
  verb: "PUT"
  authTypeEnabled: true
  scopes: []
- target: "/employee/{employeeId}"
  verb: "DELETE"
  authTypeEnabled: true
  scopes: []
```

When we try to invoke the production endpoint of the resource /employee in the above example, it does not inherit the API Level production endpoint. Instead it says resource not found.

**Expected Behaviour** : If the resource does not have a particular type of endpoint defined, it should inherit the endpoint defined at the API level.
