### ISSUE TITLE
Add downstream mTLS support

### ISSUE THREAD

**Issue by sgayangi** [wso2/apk#1839]
mTLS support at the data plane between a client and the gateway will be addressed via a field in the Authentication CR, which has been outlined below.

```
apiVersion: dp.wso2.com/v1alpha1
kind: Authentication
metadata:
  name: sand-http-bin-authentication
spec:
  default:
    mutualSSL:
      required: optional/mandatory
      certificates: 
        certificateInline: inline-cert
	secretRef: secret-ref
	configMapRef: config-map-ref
  targetRef:
    kind: API
    name: http-bin-api1
    group: “”
```
Previous implementation:
https://github.com/wso2/apk/pull/1349/files#diff-f970cdc6b0820e3730dd16ee866110459f78bb3ff1a9f0316153b862eb766f0f

Tasks

- [x] #1952
- [ ] #1953
