### ISSUE TITLE
APK generates apk-conf file which contains basepath with invalid character `=`

### ISSUE THREAD

**Issue by piraveena** [wso2/apk#2162]
**Description:**

APK generates apk-conf file which contains basepath with invalid characters.

**Steps to reproduce:**
I generated the apk-conf file for a openapi definition as shown below.
Request
```
curl -k --location 'https://api.am.wso2.com:9095/api/configurator/1.0.0/apis/generate-configuration' \
--header 'Host: api.am.wso2.com' \
--form 'definition=@"/Users/piraveena/Desktop/apk/scim2-json.json"'
```

Response
```
---
name: "SCIM 2.0 Endpoint Swagger Definition"
basePath: "/U0NJTSAyLjAgRW5kcG9pbnQgU3dhZ2dlciBEZWZpbml0aW9uMS4wLjA="
version: "1.0.0"
type: "REST"
defaultVersion: false
endpointConfigurations:
  production:
    endpoint: "https://211f-2402-4000-b18d-6813-b801-188c-eb5c-f002.ngrok-free.app//t/{tenant-domain}/scim2"
operations:
- target: "/Me"
  verb: "GET"
  secured: true
  scopes: []
- target: "/Me"
  verb: "PUT"
  secured: true
  scopes: []
- target: "/Me"
  verb: "POST"
  secured: true
  scopes: []
- target: "/Me"
  verb: "DELETE"
  secured: true
  scopes: []
- target: "/Me"
  verb: "PATCH"
  secured: true
  scopes: []
- target: "/Groups"
  verb: "GET"
  secured: true
  scopes: []
- target: "/Groups"
  verb: "POST"
  secured: true
  scopes: []
- target: "/Groups/.search"
  verb: "POST"
  secured: true
  scopes: []
- target: "/Groups/{id}"
  verb: "GET"
  secured: true
  scopes: []
- target: "/Groups/{id}"
  verb: "PUT"
  secured: true
  scopes: []
- target: "/Groups/{id}"
  verb: "DELETE"
  secured: true
  scopes: []
- target: "/Groups/{id}"
  verb: "PATCH"
  secured: true
  scopes: []
- target: "/Users"
  verb: "GET"
  secured: true
  scopes: []
- target: "/Users"
  verb: "POST"
  secured: true
  scopes: []
- target: "/Users/.search"
  verb: "POST"
  secured: true
  scopes: []
- target: "/Users/{id}"
  verb: "GET"
  secured: true
  scopes: []
- target: "/Users/{id}"
  verb: "PUT"
  secured: true
  scopes: []
- target: "/Users/{id}"
  verb: "DELETE"
  secured: true
  scopes: []
- target: "/Users/{id}"
  verb: "PATCH"
  secured: true
  scopes: []
- target: "/Bulk"
  verb: "POST"
  secured: true
  scopes: []
- target: "/ResourceTypes"
  verb: "GET"
  secured: true
  scopes: []
- target: "/ServiceProviderConfig"
  verb: "GET"
  secured: true
  scopes: []
```

When I used the same apk-conf file to deploy an API, I got the below error response.

Request
```
curl -k --location 'https://api.am.wso2.com:9095/api/deployer/1.0.0/apis/deploy' \
--header 'Host: api.am.wso2.com' \
--header 'Authorization: bearer eyJhbGciOiJSUzI1NiIsICJ0eXAiOiJKV1QiLCAia2lkIjoiZ2F0ZXdheV9jZXJ0aWZpY2F0ZV9hbGlhcyJ9.eyJpc3MiOiJodHRwczovL2lkcC5hbS53c28yLmNvbS90b2tlbiIsICJzdWIiOiI0NWYxYzVjOC1hOTJlLTExZWQtYWZhMS0wMjQyYWMxMjAwMDIiLCAiZXhwIjoxNzExNDY1NTYzLCAibmJmIjoxNzExNDYxOTYzLCAiaWF0IjoxNzExNDYxOTYzLCAianRpIjoiMDFlZWViNzktZmIwNC0xNTdlLTgxNzUtNjRlMzRjMWY2ZWQwIiwgImNsaWVudElkIjoiNDVmMWM1YzgtYTkyZS0xMWVkLWFmYTEtMDI0MmFjMTIwMDAyIiwgInNjb3BlIjoiZGVmYXVsdCJ9.ZK3H53Yz9Yn5Xd1YA-Fu28zqp6R1JQiTnNCq86oLnrQyRdbqRk4GVhf1aorakSowaJUULG5Jaygkp8li9KngsT9D2VovykNt4aglp-hkPiDlqBHKfMbeBB69HYW6snP5NjQ9BjKLC3fay1uIo1LtyKl2ATN7mlcesXJ0V54GwjUe-9zaNj9T9Nx7iOhPfTtGexcpJ7S8M5fUTsV_fknF26cNUoKpBkasevCbS6RP_pMmY_4RBWQkmk9I0YzbZuwNOOAOezHZZuI4Ep0aWObfJKIENKdxk-V-fp-gHMCtAFTsSOQ406RpwJMINSkpB2LQ3BBpXnp5Gn6ERwUH5-XV8g' \
--form 'apkConfiguration=@"/Users/piraveena/Desktop/apk/scim2.apk-conf"' \
--form 'definitionFile=@"/Users/piraveena/Desktop/apk/scim2-json.json"'
```
Error Response
```
{"code":909015, "message":"API Base Path /U0NJTSAyLjAgRW5kcG9pbnQgU3dhZ2dlciBEZWZpbml0aW9uMS4wLjA=/1.0.0 invalid", "description":"API Base Path /U0NJTSAyLjAgRW5kcG9pbnQgU3dhZ2dlciBEZWZpbml0aW9uMS4wLjA=/1.0.0 invalid", "moreInfo":{}}%    
```

I resolved this issue by removing `=` character in the basepath `"/U0NJTSAyLjAgRW5kcG9pbnQgU3dhZ2dlciBEZWZpbml0aW9uMS4wLjA="`
**Related Issues:**
