### ISSUE TITLE
Unable to attach different scopes for different resources using config ds

### ISSUE THREAD

**Issue by Tharsanan1** [wso2/apk#2340]
**Description:**
try the following conf file and check the created crs. only one scope cr is created

```

---
name: "Platform API"
basePath: "/UGxhdGZvcm0gQVBJMS4xLjA"
version: "1.1.0"
type: "REST"
defaultVersion: false
subscriptionValidation: false
endpointConfigurations:
  production:
    endpoint: "https://rest.ably.io"
operations:
- target: "/channels"
  verb: "GET"
  secured: true
  scopes: ["scope1"]
- target: "/channels/{channel_id}"
  verb: "GET"
  secured: true
  scopes: ["scope2"]
```
