### ISSUE TITLE
Support for Gateway API supported filters for HTTPRoutes

### ISSUE THREAD

**Issue by sgayangi** [wso2/apk#2378]
**Description:**
As specified in https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPRouteFilter, APK needs to be tested for the features it currently supports as well as what could potentially be supported as well.
This also needs to be added from the apk-conf level as well.

**Comment by sgayangi** [comment]
There are 5 filters in total:

- ExtensionRef
- HTTPURLRewriteFilter
- HTTPRequestMirrorFilter
- HTTPRequestRedirectFilter
- HTTPHeaderFilter

Of these 5,
- ExtensionRef
- HTTPURLRewriteFilter
- HTTPHeaderFilter
are functional in APK.

The sample HTTPRoute filters used for testing HTTPHeaderFilter are given below:

1. _requestHeaderModifier:_

```
- type: "RequestHeaderModifier"
  requestHeaderModifier:
    add:
      - name: X-Request-Custom-Header
        value: "Request-Custom-Header"
    set:
      - name: User-Agent
        value: "Replaced existing value for user agent"
    remove: ["Postman-Token"]
```

2.  _responseHeaderModifier:_
```
- type: "ResponseHeaderModifier"
  responseHeaderModifier:
    add:
      - name: X-Response-Custom-Header
        value: "Response-Custom-Header"
    set:
      - name: data
        value: "Replaced existing value for data from backend response"
    remove: ["access-control-allow-credentials"]

```

**Comment by sgayangi** [comment]
[HTTPRequestMirrorFilter](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPRequestMirrorFilter)

- Mirrors requests to the backends specified under the filter
- Needs to be given a backendRef to mirror the request to
- The request is sent to the original backendRef provided under the rule as well
- However, the responses from the backend provided under the filter will be ignored; only the response from the original backend will be sent back to the client.

Sample:
```
- type: "HTTPRequestMirrorFilter"
  requestMirror:
    backendRef:
      name: mirror-service
      port: 80

```
