### ISSUE TITLE
Upgrading APK with helm upgrade command doesn't auto deploy new pods

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/apk#2431]
### Description

Upgrading APK with helm upgrade command doesn't auto deploy new pods

### Steps to Reproduce

After doing a change to values.yaml and do the helm upgrade commands currently need to manually delete the relevant pods to make effect the change.

### Affected Component

Adapter

### Version

1.1.0

**Comment by Tharsanan1** [comment]
When I added the following change to values yaml

```
gatewayRuntime:
        analytics:
          enabled: true
          publishers:
          - enabled: true
            type: "elk"
```

Adapter and gateway runtime pods are getting restarted. Unable to reproduce this issue
