### ISSUE TITLE
Hardcoded runAsUser and runAsGroup Values in Helm Chart Cause Deployment Failures on OpenShift

### ISSUE THREAD

**Issue by steveliem** [wso2/apk#2664]
### Description

I am encountering deployment issues with the WSO2 API Platform for Kubernetes (APK) on OpenShift due to hardcoded `runAsUser` and `runAsGroup` values in the Helm chart, specifically within the `gateway-api-admission-server` deployment template. OpenShift assigns user IDs (UIDs) and group IDs (GIDs) dynamically for security reasons, and specifying these values explicitly in the container's security context leads to permission conflicts.

**Error Message:**

```
Error creating: pods "gateway-api-admission-server-7998dfb48-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, ... provider restricted-v2: .containers[0].runAsUser: Invalid value: 65532: must be in the ranges: [1001280000, 1001289999], ...]
```

### Steps to Reproduce

**Analysis:**

The deployment template includes the following security context:

```yaml
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  capabilities:
    drop:
      - "ALL"
  seccompProfile:
    type: RuntimeDefault
```

In OpenShift, the assigned UID range for the project is `1001280000/10000`, causing the hardcoded `runAsUser: 65532` and `runAsGroup: 65532` to fall outside the permissible range, resulting in deployment failures.

**Suggested Solution:**

To ensure compatibility with OpenShift's dynamic UID and GID assignment, I recommend the following modifications to the Helm chart:

1. **Remove Hardcoded Values:** Eliminate the explicit `runAsUser` and `runAsGroup` settings from the security context in the deployment templates.

2. **Utilize Service Accounts:** Define a service account for the deployment and allow OpenShift's Security Context Constraints (SCC) to assign appropriate UIDs and GIDs dynamically.

3. **Make Security Context Configurable:** Introduce Helm chart values that allow users to optionally specify `runAsUser` and `runAsGroup` if needed, defaulting to dynamic assignment when not set.

**Proposed Deployment Template Adjustment:**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api-admission-server
  namespace: {{ .Release.Namespace }}
  labels:
    name: gateway-api-admission-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gateway-api-admission-server
  template:
    metadata:
      name: gateway-api-admission-server
      labels:
        name: gateway-api-admission-server
    spec:
      serviceAccountName: {{ .Values.gatewaySystem.deployment.serviceAccountName | default "default" }}
      containers:
        - name: webhook
          image: {{ .Values.gatewaySystem.deployment.image }}
          imagePullPolicy: {{ .Values.gatewaySystem.deployment.imagePullPolicy }}
          args:
            - -logtostderr
            - --tlsCertFile=/etc/certs/cert
            - --tlsKeyFile=/etc/certs/key
            - -v=10
            - 2>&1
          ports:
            - containerPort: 8443
              name: webhook
          resources:
            limits:
              memory: 50Mi
              cpu: 100m
            requests:
              memory: 50Mi
              cpu: 100m
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/certs
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            {{- if .Values.gatewaySystem.deployment.runAsUser }}
            runAsUser: {{ .Values.gatewaySystem.deployment.runAsUser }}
            {{- end }}
            {{- if .Values.gatewaySystem.deployment.runAsGroup }}
            runAsGroup: {{ .Values.gatewaySystem.deployment.runAsGroup }}
            {{- end }}
            capabilities:
              drop:
                - "ALL"
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: webhook-certs
          secret:
            secretName: gateway-api-admission
```

**Proposed Helm Values Addition:**

```yaml
gatewaySystem:
  deployment:
    serviceAccountName: gateway-api-admission
    # Optional: Specify these only if explicit values are required
    # runAsUser: 1001280000
    # runAsGroup: 1001280000
```

By implementing these changes, the deployment will be more adaptable to environments like OpenShift, which manage security contexts dynamically, thereby preventing permission issues and facilitating smoother deployments.

Thank you for your attention to this matter. 

### Affected Component

Adapter

### Version

1.2.0

### Environment Details (with versions)

OpenShift version: 4.16.18
Kubernetes version: v1.29.8+632b078
Channel: stable-4.16

### Relevant Log Output

```shell
Error creating: pods "gateway-api-admission-server-7998dfb48-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider "quattro-monitoring-thanos-query-frontend-anyuid-scc": Forbidden: not usable by user or serviceaccount, provider "quattro-sealed-secrets-sealed-secrets": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .containers[0].runAsUser: Invalid value: 65532: must be in the ranges: [1001280000, 1001289999], provider "restricted": Forbidden: not usable by user or serviceaccount, provider "containerized-data-importer": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "loki": Forbidden: not usable by user or serviceaccount, provider "gateway-api-admission-scc": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "logging-scc": Forbidden: not usable by user or serviceaccount, provider "kubevirt-controller": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "bridge-marker": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "demo": Forbidden: not usable by user or serviceaccount, provider "scc-admin": Forbidden: not usable by user or serviceaccount, provider "scc-demo": Forbidden: not usable by user or serviceaccount, provider "linux-bridge": Forbidden: not usable by user or serviceaccount, provider "kubevirt-handler": Forbidden: not usable by user or serviceaccount, provider "fluent-bit-logging": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]
```

### Suggested Labels

APK SCC Openshift gateway-api-admission-server Helm
