### ISSUE TITLE
APIPolicy conversion from alpha3 to alpha4 not working properly

### ISSUE THREAD

**Issue by Tharsanan1** [wso2/apk#2762]
### Description

APIPolicy conversion from alpha3 to alpha4 not working properly

### Steps to Reproduce

try adding the following apipolicy and the resulted policy in the cluster does not have ai provider configured

```
apiVersion: dp.wso2.com/v1alpha3
kind: APIPolicy
metadata:
  name: llm-policy
  namespace: apk-integration-test
spec:
  override:
    aiProvider:
      name: "llm-provider"
  targetRef:
    group: gateway.networking.k8s.io
    kind: API
    name: llm-api
```

### Affected Component

Common-controller

### Version

1.3.0

### Relevant Log Output

```shell

```
