### ISSUE TITLE
InterceptorService ignores basePath of Backend

### ISSUE THREAD

**Issue by jwgmeligmeyling** [wso2/apk#2887]
### Description

When creating an Interceptor service that uses a backend with a basePath, this basePath gets ignored. There is also no alternative means of prefixing the path for an interceptor service. I guess that for the interceptor service itself a base path isn't really sensible, as it needs to comply with the OpenAPI spec, but I did expect the basePath to be applied for Interceptor services as well. That just seems a bit inconsistent.

### Steps to Reproduce

```yaml
apiVersion: dp.wso2.com/v1alpha1
kind: Backend
metadata:
  name: exact-sandbox-authenticator
spec:
  protocol: "http"
  basePath: "/api/wso2"
  services:
  - host: anubis.anubis.svc
    port: 8080
---
apiVersion: dp.wso2.com/v1alpha1
kind: APIPolicy
metadata:
  name: exact-sandbox-api-policy
spec:
  override:
    requestInterceptors:
      - name: exact-sandbox-api-interceptor-service
  targetRef:
    group: dp.wso2.com
    kind: API
    name: exact-api
---
apiVersion: dp.wso2.com/v1alpha1
kind: InterceptorService
metadata:
  name: exact-sandbox-api-interceptor-service
spec:
  backendRef:
    name: exact-sandbox-authenticator
  includes:
    - request_headers
    - invocation_context
```

### Affected Component

Router

### Version

1.2.0

### Environment Details (with versions)

I am on Amazon EKS but I guess that doesn't make a difference.

### Relevant Log Output

```shell
[2025-02-24 10:59:04.270][17][error][lua] [source/extensions/filters/http/lua/lua_filter.cc:952] script log: Invalid request interceptor service response, message: "HTTP status_code: "404", response_body: "{"error":"RESTEASY003210: Could not find resource for full path: http://anubis.anubis.svc:8080/api/v1/handle-request","requestErrors":{"error":"RESTEASY003210: Could not find resource for full path: http://anubis.anubis.svc:8080/api/v1/handle-request"},"uuid":"9ff8d991-d56c-4eef-8fcf-b3d8d90a1caf"}", request_id: "f49cda18-4717-42ba-89b2-2d06184cc5a7"


Note `http://anubis.anubis.svc:8080/api/v1/handle-request` instead of `http://anubis.anubis.svc:8080/api/wso2/api/v1/handle-request`
```
