### ISSUE TITLE
Disable API authentication security

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#391]
**Description:**
Support ability to invoke a resource/api without a token

```
apiVersion: dp.wso2.com/v1alpha1
kind: Authentication
metadata:
  name: sand-http-bin-authentication
spec:
  override:
    type: ext
    ext:
      disabled: true            
  targetRef:
    kind: HTTPRoute 
    name: sand-http-route-http-bin-api
    group: gateway.networking.k8s.io
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
