### ISSUE TITLE
Escape regex meta characters in path when type is Exact or PathPrefix

### ISSUE THREAD

**Issue by Amila-Rukshan** [wso2/apk#511]
**Description**

Use https://pkg.go.dev/regexp#QuoteMeta util function

Since all the path types are handled by regex support in envoy we need to escape regex meta characters to match literal value in Exact and PathPrefix path types.

Ex:

```
matches:
    - path:
        type: Exact
        value: /xWso2BasePath/resource-path-exact.
      method: GET
```
The dot at the end should only match dot character not any characters.
