### ISSUE TITLE
Support httpRoute rule with only backendref without matches

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#775]
**Description:**
Support the following combinations as rules in operator. 
Example from : https://gateway-api.sigs.k8s.io/guides/http-routing/

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: bar-route
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "bar.example.com"
  rules:
  - matches:
    - headers:
      - type: Exact
        name: env
        value: canary
    backendRefs:
    - name: bar-svc-canary
      port: 8080
  - backendRefs:
    - name: bar-svc
      port: 8080
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
