### ISSUE TITLE
[Adapter] gateway level interceptor support for ratelimit metadata

### ISSUE THREAD

**Issue by Amila-Rukshan** [wso2/apk#925]
**Description:**

This is to support global level interceptor service for the gateway level which is to be used for setting dynamic metadata for rate limits with metadata type descriptors.

```
apiVersion: wso2.com/v1beta1
kind: APIPolicy
metadata:
  name: pet-store-authentication-1-resource-override
spec:
  override:
    requestInterceptor:
      backendRef:
         name: global-request-intercaptor
      includes:
      - request_headers
    responseInterceptor:
      backendRef:
         name: global-response-intercaptor
      includes:
      - response_headers
  default:
    ...
  targetRef:
    kind: Gateway
    name: default 
```
